server:
  port: 8888
  servlet:
    context-path: /
spring:
#  mvc:
#    view:
#      prefix: /static/pages/
#      suffix: .html
  #    static-path-pattern: /static/**

  thymeleaf:
    mode: HTML
    prefix: classpath:/static/pages/
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false

  datasource:
    url: jdbc:sqlite:leasing.db
    driver-class-name: org.sqlite.JDBC
#    username: ''
#    password: ''
  jpa:
    show-sql: true
#    database-platform: org.hibernate.dialect.SQLiteDialect
#    generate-ddl: true
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    host: 192.168.1.211
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms




